version: '3'
services:
  jupyter-tutorial:
    image: jupyter/minimal-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD:iii
    volumes:
      - ./sql:/home/jovyan/sql/
